version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - 8000:5000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: amit
      MYSQL_PASSWORD: arsenal
      MYSQL_DB: todo
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: amit
      MYSQL_PASSWORD: arsenal
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: test@123
    volumes:
      - mysql-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-volume:


